# Making C++ Sims work R

```{r}
# Load the Rcpp package
library(Rcpp)
library(ggplot2)
```


```{r}
sourceCpp(code='
#include <Rcpp.h>
#include <RcppParallel.h>
#include <omp.h>
#include <sitmo.h>
#include <cmath>
using namespace Rcpp;

// [[Rcpp::depends(RcppParallel)]]
// [[Rcpp::depends(sitmo)]]
// [[Rcpp::plugins(openmp)]]

// Function to simulate data from SIR model

// [[Rcpp::export]]
double unif_sitmo(int seed) {
  uint32_t coreseed = static_cast<uint32_t>(seed);
  sitmo::prng eng(coreseed);
  double mx = sitmo::prng::max();
  double x = eng() / mx;
  return x;
}

double calc_dist(double* x_sim, NumericVector x) {
  double total;
  #pragma omp parallel reduction( + : total)
  {
    double inner_sum;
    #pragma omp for
    for (int i=0; i<20; i++) {
      inner_sum += pow(x[i]-x_sim[i], 2);
    }
    total += inner_sum;
  }
  return total;
}

double calc_dist_serial(double* x_sim, NumericVector x) {
  double total;
  for (int i=0; i<20; i++) {
    total += pow(x[i]-x_sim[i], 2);
  }
  return total;
}

// [[Rcpp::export]]
NumericMatrix ABC(int n, double eps, int p, NumericVector x, int ncores)
{
  
  NumericMatrix accepted_samples(n, p);
  int count = 0;
  double dist;

  #pragma omp parallel num_threads(ncores)
  {
    double theta_sim[2];
    #pragma omp for
    for (int i=0; i<n; i++) {

      #pragma omp critical
      {
      theta_sim[0] = unif_sitmo(i);
      theta_sim[1] = unif_sitmo(i+n);
      }
      
      // NumericVector I = SIR(762.0/763.0, 1.0/763.0, 0.0, theta_sim[1], theta_sim[2]);

      double S[20];
      double I[20];
      double R[20];

      S[0] = 762.0/763.0;
      I[0] = 1.0/763.0;
      R[0] = 0.0;

      for (int t = 1; t < 20; t++) {
        S[t] = S[t-1] - theta_sim[0] * S[t-1] * I[t-1];
        I[t] = I[t-1] + theta_sim[0] * S[t-1] * I[t-1] - theta_sim[1] * I[t-1];
        R[t] = R[t-1] + theta_sim[1] * I[t-1];
      }

      #pragma omp critical
      {
      dist = calc_dist_serial(I, x);
      if (dist < eps) {
        accepted_samples(i, 0) = theta_sim[0];
        accepted_samples(i, 1) = theta_sim[1];
        count++;
      }
      }
    }
  }
  
  std::cout << "Acceptance rate: " << (double)count / n << std::endl;
  return accepted_samples;
  
}

')
```

```{r}
library(pomp)
data(bsflu)
x <- bsflu$B
```

```{r}
samples <- ABC(100000000, 0.6, 2, x/763.0, 19)
```

```{r}
# filter out the zeros
samples <- samples[samples[,1] != 0,]
```

```{r}
ggplot(data=as.data.frame(samples), aes(x=V1, y=V2)) + geom_point()
```

```{r}
# plot histogram of the parameters
ggplot(data=as.data.frame(samples), aes(x=V1)) + geom_histogram()
```

```{r}
ggplot(data=as.data.frame(samples), aes(x=V2)) + geom_histogram()
```



